apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: kubernetes-hs
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            # Edit the image {username}:
            image: {username}/kubernetes-hs
            env:
               - name: TARGET
                 value: "Kubernetes World."